name: diningmanagement
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - asset/image1.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.png
  android: true
  ios: true